version: '3.4'
services:
    database:
        build: 
            context: ./database
            args:
                POSTGRES_DB: ${POSTGRES_DB}
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - shared:/shared/
        environment:
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_DB
    rabbit:
        image: rabbitmq:${RABBITMQ_VERSION}-alpine
        ports:
            - "5672:5672"
volumes:
  shared:
        